[application]
name = "learny-ui"
default_platform = "web"
out_dir = "/target/dx/learny-ui/release/web/public"
asset_dir = "assets"

[web.app]
title = "learny"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]